himanshu-03/Python-Data-Structures

- README.md
Updated the `Readme.md` file, and added contribution guidelines for the repository.
> [UPDATED] ReadMe File

- Codes/Sorting Techniques/counting_sort.py
Added the Counting Sort Algorithm using python.
#10
I have wrote the Counting Sort Algorithm which takes input of list from the user and sort that list and return it .
> Added Counting Sort

- Codes/Sorting Techniques/wave_sort.py
This PR adds a new file to implement wave in a sorted array. It fixes the issue #14
Adding Wave Sort implementation.
#14
> [ADD] wave_sort.py

- Codes/Sorting Techniques/Cycle Sort.py
Added Cycle Sort Technique #20
> Added Cycle Sort Technique

- Codes/Sorting Techniques/Bucket_Sort.py
Please review under hacktoberfest label. Thank you!
> Create Bucket_Sort.py #25

- Algorithms/graphs/dfs.py
DFS code Folder structure corrected
23
- [ ^] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [ ^] I have read and followed the **Contributing Guidelines**
> folder structure corrected for dfs 

- Algorithms/Sorting Techniques/Merge_Sort.py
Added algorithm to perform merge sort on an array.
Added file `Merge_Sort.py` inside the folder `Algorithms/Sorting Techniques` with relevant code and comments describing merge sort in brief.
> algo: merge sort

- README.md
made some changes in the description
> Update README.md (a16b8a2) issue resolved

- Codes/Sorting Techniques/Shell_Sort.py
Adds Shell Sorting
#38 
Adds Shell Sorting Algorithm to the sorting section
This code will prompt the user to enter a list of numbers separated by spaces, then apply the shell sort algorithm to sort the list, and finally, display the sorted list.
> Add Shell Sort

- Codes/Graphs/A_star.py
- Codes/Graphs/GBFS.py
added gbfs and astar search algorithms using manhattan as the heuritstic function. Created a folder called graph for the same
Added GBFS and Astar search algorithm for graphs using Manhattan as the heuristic function
> added gbfs and astar search algorithms

- Algorithms/Sorting Techniques/Bucket_Sort.py
Title :
Bucket Sorting algorithm
Issue no : 
#44 
Description
I have committed a code on the Bucket Sorting algorithm, which has the scope of improving the best case scenario of sorting algorithms to O(n + k)
Checklist
- [Yes ] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [Yes ] I have read and followed the **Contributing Guidelines**
> this fixes issue #44

- Codes/Sorting Techniques/Topological_Sort.py
- Codes/graphs/bfs.py
Added BFS Traversal Technique for Graph and Topological sort for Directed Acyclic Graph using Recursion
#36
Added Topological_Sort.py in Sorting and bfs.py in Graphs
> algo/code: 1) Added BFS traversal in graph and Topological sort for DAG

- Sorting Techniques/Cocktail_Sort.py
Added Cocktail Sort 
#57 
Cocktail Shaker Sort, also known as Bidirectional Bubble Sort, is a variation of the Bubble Sort algorithm. It works by repeatedly sorting the list in both directions, from left to right and then from right to left, which reduces the number of passes required for sorting. Elements "bubble" up and down until the list becomes fully sorted.
> algo: Added Cocktail Sort

- Searching Techniques/Jump_Search.py
Added Jump Search
#62 
Jump Search is an efficient searching algorithm for ordered lists. It divides the list into smaller blocks and jumps ahead by fixed steps to quickly reach a block that might contain the target value. It then performs a linear search within that block, providing a balance between the efficiency of binary search and the simplicity of linear search. Jump Search is especially useful for large datasets where binary search might be less efficient due to its logarithmic time complexity.
> algo: Added Jump Search

- Clustering Techniques/kmeans.py
A folder has been created by the name of Clustering Techniques. The folder should be designated for maintaining algorithms commonly used for clustering data. The kmeans algorithm has been added in this folder.
> Add kmeans algorithm

- Graphs/Prims_Algorithm_Minimum_Spanning_Tree.py
Prim's Algorithm to find the Minimum Spanning Tree.
Solves Issue #82. 
Prim’s algorithm is a Greedy algorithm. This algorithm always starts with a single node and moves through several adjacent nodes, in order to explore all of the connected edges along the way. There are many ways to implement this in Python, for example the Lazy Method, Heap Method, etc. I have implemented the Fibonnaci Heap method to optimize the algorithm as much as possible, Have added this to the Graphs Folder.
- [☑️] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [☑️] I have read and followed the **Contributing Guidelines**
> add: Prim's Algorithm to Find MST.

- Trie/Menu_Driven_Code_for_Tries.py
A trie, also known as a prefix tree, is a tree-like data structure that is used to store a dynamic set of strings. It is particularly efficient for tasks like searching for strings with a common prefix. Each node in a trie represents a character in a string.
> added trie data structure

- Queue/Menu_Driven_Code_for_Priority_Queue_Heap_implementation.py
Added Max heap based implementation of priority queue
105
I have added a file which contains the python code for max heap based implementation of priority queue in the 'queue' directory. Heap are the most efficient data structures for priority queue. Many languages like C++ use heap for their standard library priority queue implementations.
I have the followed the coding style used in rest of the repository. Like in the other files, I have written it a user menu program by which we can do queue operations from the terminal. I have made a separate class for the priority queue and used similar variable and function names as in the current priority queue implementation. This is to ensure that readers don't get confused. I have added comments where necessary.
> algo/code: Priority queue using max heap

- Clustering Techniques/Gaussain-Mixture-Model.py
I have added the Guassian Mixture Algorithm.
> added Gaussain-Mixture-Model.py

- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
I have added the code/algorithm for DBSCAN algorithm in clustering techniques
> Db scan model

- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
Added BIRCH Algortihm code to clustering Techniques
> Birch algorithm

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
Added Affinity propagation clustering algorithm
> Affinity propagation

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
i have added the code for mean shift clustering algorithm
> Mean shift clustering algorithm

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
i have added optics algorithm under the cluster techniques folder
> Optics a lgorithm

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/Agglomerative-Clustering-Algorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
- Regression-Techniques/Multiple-Linear-Regression.py
- Regression-Techniques/simple-linear-regression.py
Added the code for multiple linear regression
> Multiple linear regression

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/Agglomerative-Clustering-Algorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
- Regression-Techniques/Bayesian-Regression.py
- Regression-Techniques/Multiple-Linear-Regression.py
- Regression-Techniques/Polynomial-Regression.py
- Regression-Techniques/simple-linear-regression.py
i have added the code for bayesian regression algorithm
> Bayesian regression

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/Agglomerative-Clustering-Algorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
- Regression-Techniques/Bayesian-Regression.py
- Regression-Techniques/Isotonic-Regression.py
- Regression-Techniques/Multiple-Linear-Regression.py
- Regression-Techniques/Polynomial-Regression.py
- Regression-Techniques/Quantile-Regression.py
- Regression-Techniques/simple-linear-regression.py
I have added the isotonic regression algorithm code
> Isotonic regression

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/Agglomerative-Clustering-Algorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
- Regression-Techniques/Bayesian-Regression.py
- Regression-Techniques/Isotonic-Regression.py
- Regression-Techniques/Multiple-Linear-Regression.py
- Regression-Techniques/Polynomial-Regression.py
- Regression-Techniques/Quantile-Regression.py
- Regression-Techniques/Stepwise-Regression.py
- Regression-Techniques/simple-linear-regression.py
I have added the code for stepwise regression algorithm
> Stepwise regression

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/Agglomerative-Clustering-Algorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
- Regression-Techniques/Bayesian-Regression.py
- Regression-Techniques/Isotonic-Regression.py
- Regression-Techniques/Least-Angle-Regression.py
- Regression-Techniques/Logistic-Regression.py
- Regression-Techniques/Multiple-Linear-Regression.py
- Regression-Techniques/Polynomial-Regression.py
- Regression-Techniques/Quantile-Regression.py
- Regression-Techniques/Stepwise-Regression.py
- Regression-Techniques/simple-linear-regression.py
i have added the code for logistic regression algorithm
> Logistic regression

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/Agglomerative-Clustering-Algorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
- Regression-Techniques/Bayesian-Regression.py
- Regression-Techniques/Isotonic-Regression.py
- Regression-Techniques/Lasso-Regression.py
- Regression-Techniques/Least-Angle-Regression.py
- Regression-Techniques/Logistic-Regression.py
- Regression-Techniques/Multiple-Linear-Regression.py
- Regression-Techniques/Polynomial-Regression.py
- Regression-Techniques/Quantile-Regression.py
- Regression-Techniques/Stepwise-Regression.py
- Regression-Techniques/simple-linear-regression.py
> Lasso regression

- Clustering Techniques/Affinity-Propagation-Clustering-ALgorithm.py
- Clustering Techniques/Agglomerative-Clustering-Algorithm.py
- Clustering Techniques/BIRCH-Algorithm.py
- Clustering Techniques/DBSCAN-Model.py
- Clustering Techniques/Gaussain-Mixture-Model.py
- Clustering Techniques/Mean-Shift-Clustering-algorithm.py
- Clustering Techniques/OPTICS-algorithm.py
- Regression-Techniques/Bayesian-Regression.py
- Regression-Techniques/Isotonic-Regression.py
- Regression-Techniques/Lasso-Regression.py
- Regression-Techniques/Least-Angle-Regression.py
- Regression-Techniques/Logistic-Regression.py
- Regression-Techniques/Multiple-Linear-Regression.py
- Regression-Techniques/Polynomial-Regression.py
- Regression-Techniques/Quantile-Regression.py
- Regression-Techniques/Ridge-Regression.py
- Regression-Techniques/Stepwise-Regression.py
- Regression-Techniques/simple-linear-regression.py
i have added the code for ridge regression
> Ridge regression

- Sorting Techniques/Tim_Sort.py
_TimSort is a hybrid sorting algorithm that combines the strengths of merge sort and insertion sort. It is designed to efficiently sort a wide range of real-world data types. It maintains the relative order of equal elements in the sorted output._
> algo: Added TimSort Algorithm
